remove doc old and add template docusaurus
r2u-io/documentation pull request #24
Opened 2021-04-23 18:44 UTC by MayaraSs

2021-04-23 19:10 UTC, FelipeR2U commented
Consegue subir uma demo no `https://demos.r2u.io`? Pode seguir o esquema do `Customizer`,  mas não precisa criar o makefile

2021-04-23 19:24 UTC, FelipeR2U commented on docusaurus.config.js
> +  projectName: 'docusaurus', // Usually your repo name.
Alterar para r2u-io

2021-04-23 19:24 UTC, FelipeR2U commented on next.config.js
> +})
Pode remover

2021-04-23 19:24 UTC, FelipeR2U commented on README.md
>    <img src="https://scripts-ignition.real2u.com.br/real2u-integration/android-1.png" title="Android 1" width="200"/>
ReadME voltado para docussaurus

2021-04-23 19:24 UTC, FelipeR2U commented on docs/example.md
> +</Tabs>
Remover

2021-04-26 19:06 UTC, FelipeR2U reviewed
Tem um arquivo fantasma `.nojekyll`

2021-04-26 19:06 UTC, FelipeR2U commented on package.json
> +    "predeploy": "yarn run build",
Pode remover, aqui isso está redundante com o comando de deploy

2021-04-26 19:06 UTC, FelipeR2U commented on package.json
> +    "docusaurus": "docusaurus",
Precisa disso? Se apagar essa linha da pra fazer `yarn run docusaurus` ainda

2021-04-26 19:07 UTC, felipe-chamas approved these changes
Eu não manjo de Docusaurus pra saber como fazer o deploy, mas ele gera alguma pasta de arquivos HTML? Vc chegou a testar o `gh-pages`? 
Acho que seria melhor colocar o deploy dessa `gh-pages` no CI...

2021-04-26 19:16 UTC, MayaraSs commented
aah eu tentei sim, cheguei a abrir uma brach mas não abri pr nem nada

2021-04-26 19:16 UTC, MayaraSs commented
não fiz o deploy cheguei até a abri a branch

2021-04-26 19:17 UTC, MayaraSs commented
aah eu tentei sim, por isso estava aqueles comandos de deploy no package json

2021-04-26 19:18 UTC, MayaraSs commented
https://docusaurus.io/docs/deployment

2021-04-27 15:05 UTC, FelipeR2U requested changes
Apenas para padronizarmos o CI entre os projetos

2021-04-27 15:05 UTC, felipe-chamas commented on .github/workflows/format.yml
> +    if: github.event_name != 'push'
Não precisa, esse CI executa `on: push`

2021-04-27 15:05 UTC, felipe-chamas commented on .github/workflows/format.yml
> +          yarn install
Remover daqui-

2021-04-27 15:05 UTC, felipe-chamas commented on .github/workflows/format.yml
> +          npm run build
Trocar, igual está nos outros projetos:
```diff
-        run: |
-          if [ -e yarn.lock ]; then
-          yarn install --frozen-lockfile
-          elif [ -e package-lock.json ]; then
-          npm ci
-          else
-          npm i
-          fi
-          npm run build
+        - run: yarn install
+        - run: yarn build
```

2021-04-27 15:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +    if: github.event_name != 'pull_request'
Remover, mesmo motivo da linha 30

2021-04-27 15:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +          npm run deploy
Trocar, igual está nos outros projetos:
```diff
-        run: |
-          if [ -e yarn.lock ]; then
-          yarn install --frozen-lockfile
-          elif [ -e package-lock.json ]; then
-          npm ci
-          else
-          npm i
-          fi
-          npm run build
+        - run: yarn install
+        - run: yarn build
+        - run: yarn deploy
```

2021-04-27 15:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +  checks:
Renomear para `build`

2021-04-27 15:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +  gh-release:
Renomear para `deploy`

2021-04-27 15:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +  gh-release:
Adicionar depois dessa linha:
```diff
deploy:
+  needs: [build]
```
Para depender do estágio de build OK para fazer deploy

2021-04-27 15:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
Remover, pois o bot do Github tem acesso SSH

2021-04-27 15:09 UTC, FelipeR2U commented on .github/workflows/format.yml
> +    if: github.event_name != 'push'
Na verdade, pq vc precisaria de um Check `!onPush`?

2021-04-27 15:11 UTC, FelipeR2U commented on .github/workflows/format.yml
> +    if: github.event_name != 'push'
O que vc pode fazer é tirar o `branch: master` do começo do arquivo e colocar um `if: github.ref == 'refs/heads/master'` no `prettier` e no `deploy`

2021-04-27 15:45 UTC, MayaraSs commented on .github/workflows/format.yml
> +    if: github.event_name != 'push'
mas eu acho q não precisa tendo o brancher: master

2021-04-27 16:04 UTC, FelipeR2U commented on .github/workflows/format.yml
> +    if: github.event_name != 'push'
Tendo o `branches: -master`, tudo só vai rodar em push pra master.

2021-04-27 16:05 UTC, FelipeR2U commented on .github/workflows/format.yml
> +    if: github.event_name != 'push'
Acho que é OK pra esse repo

2021-04-27 16:05 UTC, FelipeR2U approved these changes

2021-04-27 16:06 UTC, FelipeR2U commented on .github/workflows/format.yml
>            yarn install
Tem que remover esse Yarn install, se não vai quebrar

2021-04-27 16:23 UTC, merged