edit deploy in ci
r2u-io/documentation pull request #34
Opened 2021-05-13 21:35 UTC by MayaraSs

2021-05-13 22:27 UTC, FelipeR2U requested changes

2021-05-13 22:27 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +          service_account_key: ${{ secrets.GCP_SA_KEY }}
Tem só que passar esse secret no GH

2021-05-13 22:27 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +        run: gcloud config set project docs-r2u
Projeto ficou `sdk-r2u` né?
```suggestion
        run: gcloud config set project sdk-r2u
```

2021-05-13 22:27 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +        run: gsutil cp ./build gs://doc-r2u-bucket/index.html
Tem que ser a pasta inteira:
```suggestion
        run: gsutil cp ./build/* gs://doc-r2u-bucket/
```

2021-05-13 22:33 UTC, MayaraSs commented on .github/workflows/CI.yml
> +        run: gcloud config set project docs-r2u
sim

2021-05-13 22:36 UTC, MayaraSs commented on .github/workflows/CI.yml
> +        run: gcloud config set project docs-r2u
q massa essa feature do github

2021-05-13 22:38 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +        run: gcloud config set project docs-r2u
Aprendi com o Gabão hoje tbm hahahah

2021-05-13 22:40 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +        run: gsutil cp ./build/* gs://doc-r2u-bucket/
Desculpa, vi aqui agora o jeito certo pra copiar pasta:
`gsutil -m cp -r ./build gs://doc-r2u-bucket`

(`-r` de recursivo e `-m` pra acelerar o upload em paralelo)

2021-05-14 12:15 UTC, MayaraSs commented on .github/workflows/CI.yml
> +          service_account_key: ${{ secrets.GCP_SA_KEY }}
não tem permissão para editar a settigns no github da documentation

2021-05-14 12:49 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +          service_account_key: ${{ secrets.GCP_SA_KEY }}
Vou colocar pra vc

2021-05-14 12:51 UTC, FelipeR2U commented on .github/workflows/CI.yml
> +          service_account_key: ${{ secrets.GCP_SA_KEY }}
Adicionei, acho que vai funcionar

2021-05-14 13:05 UTC, MayaraSs commented on .github/workflows/CI.yml
> +          service_account_key: ${{ secrets.GCP_SA_KEY }}
ok

2021-05-14 13:06 UTC, FelipeR2U approved these changes

2021-05-14 13:06 UTC, merged