Update version 4
r2u-io/documentation pull request #8
Opened 2020-11-05 15:39 UTC by fabio-nukui

- Update documentação para nova versão do SDK.
- Parâmentros novo `analyticsParams` em `init` é opcional, e por padrão envia eventos ao GTM, com definição de sessão igual ao padrão do GA
- Interface do `analytics` mudou para separar evento de metadados

2020-11-05 16:20 UTC, aviggiano approved these changes
showww

2020-11-05 16:37 UTC, GabrielArakaki requested changes
Acho que não tem nenhuma indicação na documentação do que são os parâmetros `dataLayerIntegration` e `sessionDurationMinutes`, como ou pra que utilizar. Acho que teria que ter eles no exemplo de `R2U.init` ou criar uma sessão separada pra explicar o Analytics.

2020-11-05 23:04 UTC, fabio-nukui commented
@GabrielArakaki Adicionei descrição no README

2020-11-06 00:21 UTC, GabrielArakaki approved these changes

2020-11-06 00:29 UTC, aviggiano approved these changes
🔝 🔝 🔝

2020-11-06 00:29 UTC, aviggiano commented on README.md
> +      sessionDurationMinutes: 30 // Tempo máximo minutes de inatividade dentro de uma sessão. Usar valor do seu Google Analytics (default: 30)
colocar em inglês

2020-11-06 03:29 UTC, merged